# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print( B - C)
print(B * C)
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.exp(B))

min_value = np.min(B)
print( "min value in matrix:", min_value)

min_value_each_row = np.min(B, axis=1)
print("min value in each row:", min_value_each_row)

min_value_each_column = np.min(B, axis=0 )
print("min value in each column", min_value_each_column)

min_index_value_whole_matrix = np.argmin(B)
print(min_index_value_whole_matrix)

min_index_value_each_row = np.argmin(B, axis=1)
print(min_index_value_each_row) 


sum_of_elements = np.sum(B)
print("summan av alla element", sum_of_elements)

mean_for_each_column = np.mean(B, axis=0)
print("mean för varje column", mean_for_each_column)

median_for_each_column = np.median(B, axis=0)
print("median för varje column", median_for_each_column)







[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
min value in matrix: 1
min value in each row: [1 4 7]
min value in each column [1 2 3]
0
[0 0 0]
summan av alla element 45
mean för varje column [4. 5. 6.]
median för varje column [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [13]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In summary, b = a.reshape((2, 3, -1)) reshapes the original array a into a 3D array with 2 groups, 3 rows in each group, and a calculated number of elements per row based on the total size of the original array. ändra denna till senare

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [14]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [16]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [17]:
def add_mult_matrices(matrix1, matrix2, operation):

    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
         ("Both inputs must be of type numpy.ndarray.")
    
    
    if operation not in ["add", "multiply"]:
        raise ValueError("oprationen måste innehålla addition eller multiplication! ")
    
    #addition
    if operation == "add":
        
        if matrix1.shape != matrix2.shape:
            raise ValueError("för addition måste båda ha samma dimenions!: ")
        return matrix1 + matrix2
    
    # multiplication
    elif operation == "multiply":
    
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("för multiplication måste columner och rader stämma med varandra!: ")
        return matrix1 @ matrix2

# test
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

#kolla så det funkar addition
add = add_mult_matrices(matrix1, matrix2, "add")
print("Matrix addition:\n",add)

# kolla så det funkar multiplication
mult = add_mult_matrices(matrix1, matrix2, "multiply")
print("Matrix multiplication:\n",mult)

Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [37]:
# uppgifter a, vilken dimension har vektorn x? den har dimensionen 2


# B
y = np.array([4, 3])

Svaret = 5 * y

print("Resultatet på B: ", Svaret)


# C


Svaret = 3 * y

print("Resultatet på C: ", Svaret)

#D

Svaret = 5 * y + 3 * y

print("Resultatet på D: ", Svaret) 

#E

Svaret = 8 * y

print("Resulatet på E: ", Svaret)

#F

Svaret = 4 * y - y

print("Resulatet på F: ", Svaret)


#G

Svaret = y_T = y.reshape(-1, 1)

print(y_T)


#H

# Svaret på H är att det inte är definerat eftersom dom inte har samma dimensioner!

#I   # efter lite googling kommre jag fram till denna ekvationen i pyhton

#beräknar normen ||y||

norm_y = np.linalg.norm(y)

print(norm_y)



#uppgiter 10.1.2

#A

#definera vektorn som en columnvektor

#B

#Den har dimensionen 4x1 (om jag fattat det hela rätt)

#C

v = np.array([3,7,0,1])

Resulatet = v * 2

print("Resulatet på uppgift B", Resulatet)


#c

Resulatet = 5 * v + 2 * v 

print("resulatet på uppgift C:", Resulatet) 


#D

Resulatet = 4 * v - 2 * v

print("Resulatet på uppgift D:", Resulatet)


#E

# den nya dimensionen blir 1x4

#F


norm_v = np.linalg.norm(v)

print(norm_v)


#uppgiter 10.1.13

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)


Svaret = norm_v1 - norm_v2


print("svaret på A:", norm_v1)
print("svaret på B:", Svaret)




Resultatet på B:  [20 15]
Resultatet på C:  [12  9]
Resultatet på D:  [32 24]
Resulatet på E:  [32 24]
Resulatet på F:  [12  9]
[[4]
 [3]]
5.0
Resulatet på uppgift B [ 6 14  0  2]
resulatet på uppgift C: [21 49  0  7]
Resulatet på uppgift D: [ 6 14  0  2]
7.681145747868608
svaret på A: 7.14142842854285
svaret på B: 3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [38]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [39]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [40]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
